server:
  port: 8080
  servlet:
    context-path: /gamehub


spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nchicong2003@gmail.com
    password: qzyjofgjnxrcwwxw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: "jdbc:mysql://localhost:3306/gamehub"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

cloudinary:
  cloud-name: dmjyr0m9b
  api-key: 577299865618647
  api-secret: ghtwO88WiVC5AkpgJbm97-IW-gQ

  spring:
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB

jwt:
  signerKey: "FpG5Qty7RiJdgZvxtMmwdEx/B1VysAWotu7Bgks2oTXCFvitcfYI1KeTHovA3Fx+"
#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springdoc: DEBUG
#    org.springframework.security: DEBUG
vnpay:
  tmnCode: "J9NG85WH"
  hashSecret: "OK81U9J58W74G9Q0V2UI9P4GDN4LQ9PZ"
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: https://yourdomain.com/vnpay-return
  version: 2.1.0
  command: pay
